// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLAFMSwWRG-BfU6hiS8wMPQhJUBgWdncU',
    appId: '1:882513945025:web:374a695505103d43a1cf40',
    messagingSenderId: '882513945025',
    projectId: 'appdegestion-502cf',
    authDomain: 'appdegestion-502cf.firebaseapp.com',
    storageBucket: 'appdegestion-502cf.firebasestorage.app',
    measurementId: 'G-4TDNKZ2321',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs8RabtWe04iowsnUWmOexR1GQuKkCvtk',
    appId: '1:882513945025:android:7a8a82ca73a8adbaa1cf40',
    messagingSenderId: '882513945025',
    projectId: 'appdegestion-502cf',
    storageBucket: 'appdegestion-502cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwFVvHAE5Fx5BUh-LHypSg-pchsIABLc',
    appId: '1:882513945025:ios:7950fc83e0f7c360a1cf40',
    messagingSenderId: '882513945025',
    projectId: 'appdegestion-502cf',
    storageBucket: 'appdegestion-502cf.firebasestorage.app',
    iosBundleId: 'com.example.miAppGestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwFVvHAE5Fx5BUh-LHypSg-pchsIABLc',
    appId: '1:882513945025:ios:7950fc83e0f7c360a1cf40',
    messagingSenderId: '882513945025',
    projectId: 'appdegestion-502cf',
    storageBucket: 'appdegestion-502cf.firebasestorage.app',
    iosBundleId: 'com.example.miAppGestion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLAFMSwWRG-BfU6hiS8wMPQhJUBgWdncU',
    appId: '1:882513945025:web:fb81e64a992ef16ca1cf40',
    messagingSenderId: '882513945025',
    projectId: 'appdegestion-502cf',
    authDomain: 'appdegestion-502cf.firebaseapp.com',
    storageBucket: 'appdegestion-502cf.firebasestorage.app',
    measurementId: 'G-7Q71P8N75Q',
  );
}
